### ISSUE TITLE
Chrome Extension Tutorial

### ISSUE THREAD

**Issue by jsenne** [sansumbrella/BCS#1]
I'm not sure why this didn't come up during my initial search, but [this tutorial](http://youtu.be/X8kFcTr_moo) is pretty straight-forward (if you can get past the guy's way of speaking, which I find really hard to ignore for some reason).  It is a walk-through of Chrome's [Getting Started Tutorial](https://developer.chrome.com/extensions/getstarted).  The issue that I'm having in following along is that clicking the icon doesn't load any images.  A little investigating has revealed that the Flickr API key being used in the JS file is invalid, and I'm not sure what to do about that.  

Edit:  It appears that I can apply for a key, but it seems like an awful lot of work for something that I don't intend to use.  Maybe there is a workaround that doesn't involve Flickr -- maybe Google Images?

**Comment by jsenne** [comment]
[Here](https://www.lullabot.com/blog/article/creating-simple-chrome-extension) is a more straight-forward tutorial that is more inline with my needs. I'd like to modify it to search the Better Business Bureau instead of the Drupal API. Is this feasible?

**Comment by sansumbrella** [comment]
Assuming the Better Business Bureau has an accessible API, absolutely.
